cmake_minimum_required(VERSION 3.16)
project(MazeMC2 CXX)
find_package(Geant4 REQUIRED)
include(${Geant4_USE_FILE})
add_executable(mazeMC mazeMC.cc)
target_link_libraries(mazeMC ${Geant4_LIBRARIES})
foreach(f check.mac run_all.sh spec_mohan.mac spec_mono14.mac spectrum_6MV.mac spectrum_6MV.csv analyze_v2.py)
  configure_file(${PROJECT_SOURCE_DIR}/${f} ${PROJECT_BINARY_DIR}/${f} COPYONLY)
endforeach()
