cmake_minimum_required(VERSION 3.16)
project(BunkerMC CXX)
find_package(Geant4 REQUIRED)
include(${Geant4_USE_FILE})
add_executable(bunkerMC bunkerMC.cc)
target_link_libraries(bunkerMC ${Geant4_LIBRARIES})
foreach(f run6MV.mac spectrum_6MV.mac run_v4_1M.mac run_v4_2M.mac run_analog.mac compare_v4.py analyze.py spectrum_6MV.csv)
  configure_file(${PROJECT_SOURCE_DIR}/${f} ${PROJECT_BINARY_DIR}/${f} COPYONLY)
endforeach()
